### PR TITLE
KOB-email-verification service first pull request

### PR DESCRIPTION
**Pull request by EtricKombat**
KOB-email-verification service first pull request

Listed are included :

- Front end with KOB logo's
- Pull / Issue templates

### CODE REVIEW

**Comment by EtricKombat** [comment]
@asa1997  , please review this pull request.

**Comment by asa1997** [comment]
@panickervinod @sumodgeorge @EtricKombat LGTM

**Comment by asa1997** [comment]
@EtricKombat  Please delete all the images used by bcgov

**Comment by asa1997** [comment]
@panickervinod @sumodgeorge @EtricKombat LGTM

**Pull request merged**
